---
- name: Validations on worker node
  hosts: 192.168.161.123
  vars:
    k8s_kubeconfig: "/home/capv/.kube/config"
  tasks:
    - name: Worker node list
      ansible.builtin.shell:
        cmd: kubectl get node -A -owide
      register: node_output
    -  debug:
             msg: "{{ node_output.stdout }}"
    - name: Get list of CNF deployed through workflow
      ansible.builtin.shell:
        cmd: kubectl get pods -A | grep nginx
      register: pod_out
    -  debug:
             msg: "{{ pod_out.stdout }}"
    - name: Read the kubeconfig file for workload cluster
      ansible.builtin.file:
        path: /home/capv/.kube/config
        register: workload_kubeconfig
    - debug:
        var: workload_kubeconfig.content
